# Source of truth: claude-statusline — the claude-setup copy is generated by
# scripts/sync-statusline-skill.ps1

import sys, re, io, os

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

# ── Targets ──────────────────────────────────────────────────────
# The deployed copy is what settings.json runs, so it is always written — that is
# what makes /statusline take effect immediately. When this skill sits inside the
# claude-statusline repo, the repo source is written too, so the two never drift.
# Resolved from __file__ rather than the cwd: the skill can be invoked from any
# subdirectory, and a cwd-based lookup would silently pick the wrong file.
DEPLOYED  = os.path.join(os.path.expanduser("~"), ".claude", "statusline.py")
SKILL_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_COPY = os.path.join(os.path.abspath(os.path.join(SKILL_DIR, "..", "..", "..")), "statusline.py")

def _is_statusline(path):
    """A readable statusline.py, identified by its config vars."""
    if not os.path.isfile(path):
        return False
    try:
        with open(path, "r", encoding="utf-8") as f:
            return 'COLOR_SCHEME = "' in f.read()
    except OSError:
        return False

TARGETS = []
for _path in (DEPLOYED, REPO_COPY):
    _key = os.path.normcase(os.path.realpath(_path))
    if _is_statusline(_path) and _key not in [os.path.normcase(os.path.realpath(t)) for t in TARGETS]:
        TARGETS.append(_path)

if not TARGETS:
    print(f"No statusline.py found at {DEPLOYED} — run the deploy script first.")
    sys.exit(1)

STYLES = {"minimal", "powerline", "powerline-short"}
SCHEMES = {"default", "banana-blueberry", "catppuccin-frappe", "catppuccin-latte", "catppuccin-macchiato", "catppuccin-mocha"}
RATE_OPTS = {
    "rate-all":  "all",
    "rate-5h":   "5h",
    "rate-7d":   "7d",
    "rate-none": "none",
}

FRIENDLY = {
    "STYLE":        "Style",
    "COLOR_SCHEME": "Scheme",
    "SHOW_RATE_LIMITS": "Rate limits",
}

STYLE_COMMENT  = '# "minimal" | "powerline" | "powerline-short"'
SCHEME_COMMENT = '# "default" | "banana-blueberry" | "catppuccin-frappe" | "catppuccin-latte" | "catppuccin-macchiato" | "catppuccin-mocha"'
RATE_COMMENT   = '# "all" | "5h" | "7d" | "none"'

# ── Read current state ───────────────────────────────────────────
with open(TARGETS[0], "r", encoding="utf-8") as f:
    content = f.read()

def _read_str(var):
    m = re.search(rf'{var} = "([^"]*)"', content)
    return m.group(1) if m else "?"

cur_style   = _read_str("STYLE")
cur_scheme  = _read_str("COLOR_SCHEME")
cur_rate    = _read_str("SHOW_RATE_LIMITS")

# ── No args → help with current state ────────────────────────────
if len(sys.argv) < 2:
    print(f"""/statusline — Configure statusline appearance

  Style:    minimal | powerline | powerline-short
  Scheme:   default | banana-blueberry | catppuccin-frappe
            | catppuccin-latte | catppuccin-macchiato | catppuccin-mocha
  Rate:     rate-all | rate-5h | rate-7d | rate-none

  Current:  {cur_style} · {cur_scheme} · rate: {cur_rate}

  Examples: /statusline powerline
            /statusline rate-none""")
    sys.exit(0)

# ── Deduplicate: last-wins per variable ──────────────────────────
seen_vars = {}  # var_name → (index, arg)
raw_args = sys.argv[1:]

for i, arg in enumerate(raw_args):
    if arg in STYLES:
        seen_vars["STYLE"] = (i, arg)
    elif arg in SCHEMES:
        seen_vars["COLOR_SCHEME"] = (i, arg)
    elif arg in RATE_OPTS:
        seen_vars["SHOW_RATE_LIMITS"] = (i, arg)
    else:
        seen_vars[f"_error_{i}"] = (i, arg)

# ── Process deduplicated args in original order ──────────────────
changes = []
errors = []
subs = []  # (var, new_value, comment) — applied to every target below

for var, (_, arg) in sorted(seen_vars.items(), key=lambda x: x[1][0]):
    if var.startswith("_error_"):
        errors.append(f"Unknown: `{arg}` — run /statusline for help")
        continue

    label = FRIENDLY[var]

    if arg in STYLES:
        new_val, comment = arg, STYLE_COMMENT
    elif arg in SCHEMES:
        new_val, comment = arg, SCHEME_COMMENT
    else:
        new_val, comment = RATE_OPTS[arg], RATE_COMMENT

    old = _read_str(var)
    if old == new_val:
        changes.append(f"{label}: already `{new_val}`")
        continue

    subs.append((var, new_val, comment))
    changes.append(f"{label}: {old} → {new_val}")

# ── Write ────────────────────────────────────────────────────────
# Each target is substituted into its own content, never overwritten with another
# target's, so unrelated local edits in one copy survive.
written = 0
if subs:
    for target in TARGETS:
        with open(target, "r", encoding="utf-8") as f:
            text = f.read()
        for var, new_val, comment in subs:
            text = re.sub(rf'{var} = "[^"]*".*', f'{var} = "{new_val}"  {comment}', text)
        with open(target, "w", encoding="utf-8") as f:
            f.write(text)
        written += 1

for line in changes:
    print(line)
if written > 1:
    print(f"Written to {written} files (deployed + repo source)")
for line in errors:
    print(line, file=sys.stderr)
    print(line)  # also to stdout so Claude sees it
